// Generated by https://quicktype.io

export interface Movie {
    _type: Type
    id: number
    cinema: number
    blockbuster: boolean
    title: string
    subtitle: null | string
    hasTrailer: boolean
    attributes: string[]
    showtimes: Showtime[]
    date?: string
    movie?: number
    relatedShows?: number[]
    poster_preload: string
    poster: string
    trailer?: number
    detailLink: string
    startDate?: string
    screeningWeek?: number
    event?: number
    endDate?: null
    showtimeSchedule?: ShowtimeSchedule
}

export enum Type {
    Event = "event",
    Movie = "movie",
}

export interface ShowtimeSchedule {
    id: number
    datetime: string
    text: string
}

export interface Showtime {
    id: number
    name: string
    cinema: number
    datetime: string
    emv: number | null
    fsk: number
    systemId: string
    system: System
    show: number
    attributes: string[]
    screen: number
}

export enum System {
    Vista = "vista",
}
